### PR TITLE
UDict + cmp_generator

### LINKED ISSUE #1: UsefulDicts
UsefulDict object

### LINKED ISSUE #2: Add compare magic methods generator + Comparable protocol
Example:
```py
@cmp_generator
class A:
   def __cmp__(self, other: ...) -> int: ...

def func(a: Comparable, b: Comparable):
   print(a > b)
```

### LINKED ISSUE #7: Add `__i...__()` generator
Generate `__iadd__`, `__isub__` and other magic methods. You should add `__add__`, `__sub__` and other methods.

```py
@i_generator # Auto generate __iadd__()
class A:
    def __add__(self, other): ...
```

### LINKED ISSUE #8: UDict indices and keys conflict
You can get a value from a dict by using `dict[x]` with either index or a key.

```py
dict = UDict(foo=1, bar=2)
dict["foo"] # 1
dict[1] # 1
dict[-1] # 2
```

In inbuilt dicts, you can actually use `int`s as a key:

```py
dict = {1: "foo", 2: "bar"}
dict[1] # foo
dict[2] # bar
```

So, if you do something like this, you will get the value by the key, not index:

```py
dict = UDict({2: "foo", 1: "bar"})
dict[1] # bar
```

But what if you _reeeeally_ want to get a value by an index, not a key? This definitely needs a fix.

I propose the following solution:

```py
dict.get(index=1) # foo
dict.get(key=1) # bar
```

### PR DESCRIPTION
**Pull request by bleudev**
Checklist:
- [x] UDict
- [x] #8
- [x] cmp_generator
- [x] i_generator

closes #1
closes #2
closes #7 
closes #8

### CODE REVIEW

**Review by moontr3 — APPROVED** [review]
lgtm

**Review by moontr3 — CHANGES_REQUESTED** [review]
I'd change some things honestly:

- Make indices start at 0 instead of 1
- Getting the `default` attribute in the `UDict.get(default=0)` function, not when the UDict is initialised (eg. `UDict(default=0)`)

**Comment by bleudev** [comment]
> I'd change some things honestly:
> 
> * Make indices start at 0 instead of 1
> * Getting the `default` attribute in the `UDict.get(default=0)` function, not when the UDict is initialised (eg. `UDict(default=0)`)

1. Not. It's feature
2. I'll do this

**Review by moontr3 — CHANGES_REQUESTED** [review]
I'd remove the `default` kw arg from the `UDict.__init__()`, since if you want to pass in a key named `default`, you'll need to do that using a dict instead of keyword args, which can lead to bad code readability.

And I'd really change the indices to start from 0 for convenience.

Other than that everything looks good.

**Comment by bleudev** [comment]
> I'd remove the `default` kw arg from the `UDict.__init__()`, since if you want to pass in a key named `default`, you'll need to do that using a dict instead of keyword args, which can lead to bad code readability.
> 
> And I'd really change the indices to start from 0 for convenience.
> 
> Other than that everything looks good.

No, i don't want change this things

**Review by moontr3 — APPROVED** [review]
You do you then

**Comment by bleudev** [comment]
> You do you then

Thanks for approval!

**Review by TheHakerTech — APPROVED** [review]

**Pull request merged**
